//
//  ReportPreviewViewController.swift
//  Reporter
//
//  Created by Grant Singleton on 1/3/20.
//  Copyright © 2020 Grant Singleton. All rights reserved.
//

import UIKit
import PDFKit
import MessageUI

class ReportPreviewViewController: UIViewController, MFMailComposeViewControllerDelegate {
    
    var PDF: Data = Data()
    var date: String?
    @IBOutlet weak var emailButton: UIBarButtonItem!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        emailButton.title = ""
        emailButton.image = UIImage(named: "email")

        if (PDF.isEmpty) {
            //display an error message
        } else {
            // display the pdf
            displayPDF()
        }
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */
    
    func displayPDF() {
        
        let pdfView = PDFView()

        pdfView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(pdfView)

        pdfView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor).isActive = true
        pdfView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor).isActive = true
        pdfView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor).isActive = true
        pdfView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor).isActive = true
        
        pdfView.autoScales = true
        
        pdfView.document = PDFDocument(data: PDF)
    }
    
    //MARK: Actions
    @IBAction func emailReport(_ sender: UIBarButtonItem) {
        
        if !MFMailComposeViewController.canSendMail() {
            print("Mail services are not available")
            return
        }
        
        let composeMailViewController = MFMailComposeViewController()
        composeMailViewController.mailComposeDelegate = self
        
        composeMailViewController.setSubject((date ?? "Daily Field") + " Report")
        composeMailViewController.setMessageBody("This report was generated by Reporter", isHTML: false)
        composeMailViewController.addAttachmentData(PDF, mimeType: "application/pdf", fileName: "pdfReport")
        
        self.present(composeMailViewController, animated: true, completion: nil)
    }
    

}
